apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    app.kubernetes.io/name: db
spec:
  ports:
  - name: db
    port: 3306
  clusterIP: None
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: db-read
  labels:
    app: db
    app.kubernetes.io/name: db
    readonly: "true"
spec:
  ports:
  - name: db
    port: 3306
  selector:
    app: db