apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: codehub-local:40000/db:2.0
        name: db
        resources: {}
        volumeMounts: 
          - name: init-sql
            mountPath: /docker-entrypoint-initdb.d/01.sql
            subPath: 01.sql
          - name: my-cnf
            mountPath: /etc/my.cnf
            subPath: my.cnf
          - name: my-data
            mountPath: /var/lib/mysql
            subPath: mysql
      volumes:
        - name: init-sql
          configMap:
            name: init-sql
        - name: my-cnf
          configMap:
            name: my-cnf
  volumeClaimTemplates:
  - metadata:
      name: my-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
    
