apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: {{ .Values.containers.image }}
        name: frontend
        resources: {}
        volumeMounts: 
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: index-html
            mountPath: /usr/share/nginx/html/index.php
            subPath: index.php

      volumes:
        - name: nginx-config
          configMap:
            name: default-conf
        - name: index-html
          configMap:
            name: index-html
