apiVersion: v1
data:
  default.conf: "upstream app1{\n    server app:6000;\n}\n\nserver {\n    listen       80;\n
    \   listen  [::]:80;\n    server_name  localhost;\n\n    #access_log  /var/log/nginx/host.access.log
    \ main;\n    \n    location /personbook {\n        proxy_pass http://app1/; \n
    \   }\n\n    location / {\n        root   /usr/share/nginx/html;\n        index
    \ index.htm index.html;\n    }\n\n    #error_page  404              /404.html;\n\n
    \   # redirect server error pages to the static page /50x.html\n    #\n    error_page
    \  500 502 503 504  /50x.html;\n    location = /50x.html {\n        root   /usr/share/nginx/html;\n
    \   }\n\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: default-conf
